config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'static_pages#home'
  get '/lakevilla' => 'static_pages#lakevilla'
  get '/location' => 'static_pages#location'
  get '/genplan' => 'static_pages#genplan'
  get '/gallery' => 'static_pages#gallery'
  get '/prices' => 'static_pages#prices'
  get '/infrastructure' => 'static_pages#infrastructure'
  get '/houses' => 'static_pages#houses'

  get '/realization' => 'static_pages#realization'
  get '/indivdesign' =>  'static_pages#indivdesign'
  get '/finishedhouse' =>  'static_pages#finishedhouse'
  get '/buildingprocess' =>  'static_pages#buildingprocess'
  get '/improvement' =>  'static_pages#improvement'
  get '/lakevilla' =>  'static_pages#lakevilla'
  get '/kivarinruchey' =>  'static_pages#kivarinruchey'
  get '/zerkalniy' =>  'static_pages#zerkalniy'
  get '/contacts' => 'static_pages#contacts'
  root 'static_pages#home'
  resources :sales do
    resources :gallerysales
    resources :relcovers
    resources :pics
  end
  resources :sheets do
    resources :smodels
  end
  resources :comments
  resources :models do
    resources :model_images
    resources :model_picture
    resources :model_galleries
  end
  namespace :admin do
    resources :model_tables
    resources :sales do
      resources :relcovers
      resources :pics
    end
    resources :tags
    resources :covers
    resources :pictures
    resources :model_pictures
    resources :models do
      resources :model_images
      resources :model_galleries
    end
    resources :sheets do
      resources :smodels
    end
    resources :galleries
    resources :tables

    resources :comments
    get '/home' => 'static_pages#home'
    get '/lakevilla' => 'static_pages#lakevilla'
    get '/location' => 'static_pages#location'
    get '/genplan' => 'static_pages#genplan'
    get '/infrastructure' => 'static_pages#infrastructure'
    get '/houses' => 'static_pages#houses'
    root 'static_pages#home'
    get '/nordplan' => 'static_pages#nordplan'
    get '/building' => 'static_pages#building'
    get '/villages' => 'static_pages#villages'
    get '/gallery' => 'static_pages#gallery'
    get '/prices' => 'static_pages#prices'
    get '/earth' => 'static_pages#earth'
    get '/projects' => 'static_pages#projects'
    get '/sale' => 'static_pages#sale'
    get '/gazobeton' =>  'static_pages#gazobeton'
    get '/karkas' =>  'static_pages#karkas'
    get '/krovlya' =>  'static_pages#krovlya'
    get '/monolit' =>  'static_pages#monolit'
    get '/systems' =>  'static_pages#systems'
    get '/fundament' =>  'static_pages#fundament'
    get '/europeanprojects' =>  'static_pages#europeanprojects'
    get '/nordplanprojects' =>  'static_pages#nordplanprojects'
    get '/indivdesign' =>  'static_pages#indivdesign'
    get '/finishrdhouse' =>  'static_pages#finishrdhouse'
    get '/buildingprocess' =>  'static_pages#buildingprocess'
    get '/improvement' =>  'static_pages#improvement'
    get '/lakevilla' =>  'static_pages#lakevilla'
    get '/kivarinruchey' =>  'static_pages#kivarinruchey'
    get '/zerkalniy' =>  'static_pages#zerkalniy'
    get '/contacts' => 'static_pages#contacts'
    get '/realization' => 'static_pages#realization'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, :title, :text, presence: true
end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < Admin::ApplicationController
  def index
    @comments = Comment.all
    @sheets = Sheet.all
    @pictures = Picture.all
  end
  def new
    @comment = Comment.new
  end
  def create
    @comment = Comment.new(comment_params)
    @comment.save
  end
  def edit
  @comment = Comment.find(params[:id])
  end
  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
    redirect_to admin_comments_path
    else
    render 'edit'
    end
  end
  def destroy
  @comment = Comment.find(params[:id])
  @comment.destroy
  redirect_to admin_comments_path
  end
  private
  def comment_params
    params.require(:comment).permit(:name, :title, :text)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def index
    @comments = Comment.all
  end
  def new
    @pictures = Picture.all
    @comment = Comment.new
    @sheets = Sheet.all
  end
  def create
    @comment = Comment.new(comment_params)
    @comment.save
  end
  private
  def comment_params
    params.require(:comment).permit(:name, :title, :text)
  end
end

app/views/admin/comments/edit.html.erb
<%= form_for [@comment], html: { multipart: true } do |form| %>
  <div class="row">
    <div class="col-sm-4">
      <%= form.label :Имя %>
      <%= form.text_field :name, class: 'form-control' %>
      <%= form.label :Тема %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <%= form.label :Отзыв %>
      <br>
      <%= form.text_area :text %>
      <br>
    </div>
    <div class="col-sm-4">
      
    </div>
  </div>

    <%= form.submit 'Создать', class: 'btn btn-default'%>
<% end %>

app/views/admin/comments/index.html.erb
<% @pictures.where(id:43).each do |picture| %>
    <%= image_tag picture.photo.url(:big) , class: 'img-responsive' %>
    <%= link_to 'Редактировать',edit_admin_picture_path(picture), class: 'btn btn-default' %>
<%end %>
<br> <%= link_to 'Создать', new_admin_sheet_path, class: 'btn btn-default' %>
<% @sheets.where(item:'Контакты').each do |sheet| %>
  <%= image_tag sheet.photo.url(:big) %>
<h2><%= sheet.title %></h2>
<p class="p1"><%= sheet.text.html_safe %>
  <%= link_to 'Редактировать', edit_admin_sheet_path(sheet), class: 'btn btn-default' %>

  <%= link_to 'Удалить', admin_sheet_path(sheet), class: 'btn btn-default',
  method: :delete,
  data: { confirm: 'Продолжить?' } %>
<% end %>
<% @comments.each do |comment| %>
<div class="row">
  <div class="col-sm-3">
    <span>Имя :</span>  <%= comment.name %>
    <span>Тема :</span><%= comment.title %>
    <span>Почта :</span><%= comment.mail %>
    <span>Телефон :</span><%= comment.phone %>
  </div>
  <div class="col-sm-6" style="display:inline">
    <span>Отзыв :</span><%= comment.text %>
  </div>
    <%= link_to 'Удалить', admin_comments_path(comment), class: 'btn btn-default',
    method: :delete,
    data: { confirm: 'Продолжить?' } %>
  </div>
</div>
<% end %>

app/views/admin/comments/new.html.erb
<%= form_for [@comment], html: { multipart: true } do |form| %>
  <div class="row">
    <div class="col-sm-4">
      <%= form.label :Имя %>
      <%= form.text_field :name, class: 'form-control' %>
      <%= form.label :Тема %>
      <%= form.text_field :title, class: 'form-control' %>
    </div>
    <div class="col-sm-4">
      <%= form.label :Отзыв %>
      <br>
      <%= form.text_area :text %>
      <br>
    </div>
    <div class="col-sm-4">

    </div>
  </div>

    <%= form.submit 'Создать', class: 'btn btn-default'%>
<% end %>