config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'static_pages#home'
  get '/lakevilla' => 'static_pages#lakevilla'
  get '/location' => 'static_pages#location'
  get '/genplan' => 'static_pages#genplan'
  get '/gallery' => 'static_pages#gallery'
  get '/prices' => 'static_pages#prices'
  get '/infrastructure' => 'static_pages#infrastructure'
  get '/houses' => 'static_pages#houses'

  get '/realization' => 'static_pages#realization'
  get '/indivdesign' =>  'static_pages#indivdesign'
  get '/finishedhouse' =>  'static_pages#finishedhouse'
  get '/buildingprocess' =>  'static_pages#buildingprocess'
  get '/improvement' =>  'static_pages#improvement'
  get '/lakevilla' =>  'static_pages#lakevilla'
  get '/kivarinruchey' =>  'static_pages#kivarinruchey'
  get '/zerkalniy' =>  'static_pages#zerkalniy'
  get '/contacts' => 'static_pages#contacts'
  root 'static_pages#home'
  resources :sales do
    resources :gallerysales
    resources :relcovers
    resources :pics
  end
  resources :sheets do
    resources :smodels
  end
  resources :comments
  resources :models do
    resources :model_images
    resources :model_picture
    resources :model_galleries
  end
  namespace :admin do
    resources :model_tables
    resources :sales do
      resources :relcovers
      resources :pics
    end
    resources :tags
    resources :covers
    resources :pictures
    resources :model_pictures
    resources :models do
      resources :model_images
      resources :model_galleries
    end
    resources :sheets do
      resources :smodels
    end
    resources :galleries
    resources :tables

    resources :comments
    get '/home' => 'static_pages#home'
    get '/lakevilla' => 'static_pages#lakevilla'
    get '/location' => 'static_pages#location'
    get '/genplan' => 'static_pages#genplan'
    get '/infrastructure' => 'static_pages#infrastructure'
    get '/houses' => 'static_pages#houses'
    root 'static_pages#home'
    get '/nordplan' => 'static_pages#nordplan'
    get '/building' => 'static_pages#building'
    get '/villages' => 'static_pages#villages'
    get '/gallery' => 'static_pages#gallery'
    get '/prices' => 'static_pages#prices'
    get '/earth' => 'static_pages#earth'
    get '/projects' => 'static_pages#projects'
    get '/sale' => 'static_pages#sale'
    get '/gazobeton' =>  'static_pages#gazobeton'
    get '/karkas' =>  'static_pages#karkas'
    get '/krovlya' =>  'static_pages#krovlya'
    get '/monolit' =>  'static_pages#monolit'
    get '/systems' =>  'static_pages#systems'
    get '/fundament' =>  'static_pages#fundament'
    get '/europeanprojects' =>  'static_pages#europeanprojects'
    get '/nordplanprojects' =>  'static_pages#nordplanprojects'
    get '/indivdesign' =>  'static_pages#indivdesign'
    get '/finishrdhouse' =>  'static_pages#finishrdhouse'
    get '/buildingprocess' =>  'static_pages#buildingprocess'
    get '/improvement' =>  'static_pages#improvement'
    get '/lakevilla' =>  'static_pages#lakevilla'
    get '/kivarinruchey' =>  'static_pages#kivarinruchey'
    get '/zerkalniy' =>  'static_pages#zerkalniy'
    get '/contacts' => 'static_pages#contacts'
    get '/realization' => 'static_pages#realization'
  end
end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :name, :title, :text, presence: true
end

app/models/cover.rb
class Cover < ApplicationRecord
  include Paperclip::Glue
  belongs_to :model
  has_attached_file :photo, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

end

app/models/gallery.rb
class Gallery < ApplicationRecord
  include Paperclip::Glue

  has_attached_file :photo, styles: { big: "1200x900>", medium: "400x300>", small: "100x75>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  validates :photo, attachment_presence: true
end

app/models/model.rb
class Model < ApplicationRecord
  include Paperclip::Glue
  has_many :covers, dependent: :destroy
  has_many :model_images, dependent: :destroy
  has_many :model_tables, dependent: :destroy
  has_many :model_galleries, dependent: :destroy
  has_one :model_picture, dependent: :destroy
  accepts_nested_attributes_for :model_tables, reject_if: :all_blank
  accepts_nested_attributes_for :covers, reject_if: :all_blank
  has_attached_file :photo, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  has_attached_file :simage, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  has_attached_file :plan
  validates :photo, attachment_presence: true
  validates :title, presence: true
end

app/models/model_gallery.rb
class ModelGallery < ApplicationRecord
  include Paperclip::Glue
  belongs_to :model
  has_attached_file :photo, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/model_image.rb
class ModelImage < ApplicationRecord
  include Paperclip::Glue
  belongs_to :model
  has_attached_file :photo, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/model_picture.rb
class ModelPicture < ApplicationRecord
  include Paperclip::Glue
  belongs_to :model
  has_attached_file :photo, styles: { big: "1200x500>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/model_table.rb
class ModelTable < ApplicationRecord
  belongs_to :model
end

app/models/pic.rb
class Pic < ApplicationRecord
  include Paperclip::Glue
  has_attached_file :photo, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  belongs_to :sale
end

app/models/picture.rb
class Picture < ApplicationRecord
  include Paperclip::Glue

  has_attached_file :photo, styles: { big: "1200x500>", medium: "1000x657>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  validates :photo, attachment_presence: true
end

app/models/relcover.rb
class Relcover < ApplicationRecord
  include Paperclip::Glue
  has_attached_file :photo, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  belongs_to :sale
end

app/models/sale.rb
class Sale < ApplicationRecord
  include Paperclip::Glue
  has_many :tables
  has_many :relcovers
  has_many :pics
  has_attached_file :photo, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  has_attached_file :map, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  has_attached_file :bimage, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  has_attached_file :simage, styles: { big: "1200x500>", medium: "1000x657>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  accepts_nested_attributes_for :tables, reject_if: proc { |attributes| attributes['column1'].blank? }
  accepts_nested_attributes_for :pics, reject_if: :all_blank
  accepts_nested_attributes_for :relcovers, reject_if: :all_blank
  validates :photo, attachment_presence: true
  validates :title, :text, presence: true
end

app/models/sheet.rb
class Sheet < ApplicationRecord
  include Paperclip::Glue
  has_many :smodels, dependent: :destroy
  has_attached_file :photo, styles: { big: "1200x500>", medium: "1000x657>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  has_attached_file :img1, styles: { big: "1200x900>", medium: "800x600>", small: "400x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  has_attached_file :img2, styles: { big: "1200x900>", medium: "800x600>", small: "400x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
  has_attached_file :img3, styles: { big: "1200x900>", medium: "800x600>", small: "400x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/smodel.rb
class Smodel < ApplicationRecord
  include Paperclip::Glue
  belongs_to :sheet
  has_attached_file :photo, styles: { big: "1200x500>", medium: "1000x657>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/
end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :sale
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/helpers/covers_helper.rb
module CoversHelper
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/layouts/admin/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NORD PLAN</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'admin/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'admin/application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Настройки</a>
          </div>
          <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
              <li><%= active_link_to 'На сайт', root_path, active: :exact, wrap_tag: :li %></li>
              <li><%= active_link_to 'Галерея', admin_galleries_path, wrap_tag: :li %></li>
              <li><%= active_link_to 'Теги', admin_tags_path, wrap_tag: :li %></li>
              <li><%= active_link_to 'Дома', admin_sales_path, wrap_tag: :li %></li>
              <li><%= active_link_to 'Картинки', admin_pictures_path, wrap_tag: :li %></li>
              <li><%= active_link_to 'Отзывы', admin_comments_path, wrap_tag: :li %></li>
            </ul>
          </div>
              <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
              <li>
                <%= active_link_to 'LAKE VILLA', '/admin/home' , wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'РАСПОЛОЖЕНИЕ', '/admin/location', wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'ГЕНПЛАН', '/admin/genplan', wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to  'ДОМА', '/admin/houses', wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'ИНФРАСТРУКТУРА', '/admin/infrastructure', wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'ЦЕНЫ', '/admin/prices', wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'ГАЛЕРЕЯ', '/admin/gallery', wrap_tag: :li %>
              </li>
              <li>
                <%= active_link_to 'КОНТАКТЫ', '/admin/contacts', wrap_tag: :li %>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      <%= yield %>
    </div>
  </body>
</html>

app/views/layouts/partials/_navbar.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <a href="tel:+78124085453" class="tel">8 (812) 408 54 53</a>
    <div class="row">
    <div class="col-sm-2">
    <a href="/home">
  <%= image_tag(image_path('logo.jpg'), alt: 'nordplan', class: 'logo hidden-xs') %>
  </a>
    </div>
    <div class="col-sm-10">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/home">
        <span class="visible-xs">LAKE VILLA</span>
      </a>
    </div>
    <div id="navbar" class="navbar-collapse collapse" aria-expanded="false" style="height: 1px;">
      <ul class="nav navbar-nav navbar-right">
    <!--    <li><%= active_link_to 'ГЛАВНАЯ', '/home'%></li> -->
        <li><%= active_link_to 'LAKE VILLA', '/home'%></li>
        <li><%= active_link_to 'РАСПОЛОЖЕНИЕ', '/location'%></li>
        <li><%= active_link_to 'ГЕНПЛАН', '/genplan'%></li>
        <li><%= active_link_to 'ДОМА', '/houses'%></li>
        <li><%= active_link_to 'ИНФРАСТРУКТУРА', '/infrastructure'%></li>
        <li><%= active_link_to 'ЦЕНЫ', '/prices'%></li>
        <li><%= active_link_to 'ГАЛЕРЕЯ', '/gallery'%></li>
      </ul>
    </div>
  </div>
  </div>
  </div>
</nav>