config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'static_pages#home'
  get '/lakevilla' => 'static_pages#lakevilla'
  get '/location' => 'static_pages#location'
  get '/genplan' => 'static_pages#genplan'
  get '/gallery' => 'static_pages#gallery'
  get '/prices' => 'static_pages#prices'
  get '/infrastructure' => 'static_pages#infrastructure'
  get '/houses' => 'static_pages#houses'

  get '/realization' => 'static_pages#realization'
  get '/indivdesign' =>  'static_pages#indivdesign'
  get '/finishedhouse' =>  'static_pages#finishedhouse'
  get '/buildingprocess' =>  'static_pages#buildingprocess'
  get '/improvement' =>  'static_pages#improvement'
  get '/lakevilla' =>  'static_pages#lakevilla'
  get '/kivarinruchey' =>  'static_pages#kivarinruchey'
  get '/zerkalniy' =>  'static_pages#zerkalniy'
  get '/contacts' => 'static_pages#contacts'
  root 'static_pages#home'
  resources :sales do
    resources :gallerysales
    resources :relcovers
    resources :pics
  end
  resources :sheets do
    resources :smodels
  end
  resources :comments
  resources :models do
    resources :model_images
    resources :model_picture
    resources :model_galleries
  end
  namespace :admin do
    resources :model_tables
    resources :sales do
      resources :relcovers
      resources :pics
    end
    resources :tags
    resources :covers
    resources :pictures
    resources :model_pictures
    resources :models do
      resources :model_images
      resources :model_galleries
    end
    resources :sheets do
      resources :smodels
    end
    resources :galleries
    resources :tables

    resources :comments
    get '/home' => 'static_pages#home'
    get '/lakevilla' => 'static_pages#lakevilla'
    get '/location' => 'static_pages#location'
    get '/genplan' => 'static_pages#genplan'
    get '/infrastructure' => 'static_pages#infrastructure'
    get '/houses' => 'static_pages#houses'
    root 'static_pages#home'
    get '/nordplan' => 'static_pages#nordplan'
    get '/building' => 'static_pages#building'
    get '/villages' => 'static_pages#villages'
    get '/gallery' => 'static_pages#gallery'
    get '/prices' => 'static_pages#prices'
    get '/earth' => 'static_pages#earth'
    get '/projects' => 'static_pages#projects'
    get '/sale' => 'static_pages#sale'
    get '/gazobeton' =>  'static_pages#gazobeton'
    get '/karkas' =>  'static_pages#karkas'
    get '/krovlya' =>  'static_pages#krovlya'
    get '/monolit' =>  'static_pages#monolit'
    get '/systems' =>  'static_pages#systems'
    get '/fundament' =>  'static_pages#fundament'
    get '/europeanprojects' =>  'static_pages#europeanprojects'
    get '/nordplanprojects' =>  'static_pages#nordplanprojects'
    get '/indivdesign' =>  'static_pages#indivdesign'
    get '/finishrdhouse' =>  'static_pages#finishrdhouse'
    get '/buildingprocess' =>  'static_pages#buildingprocess'
    get '/improvement' =>  'static_pages#improvement'
    get '/lakevilla' =>  'static_pages#lakevilla'
    get '/kivarinruchey' =>  'static_pages#kivarinruchey'
    get '/zerkalniy' =>  'static_pages#zerkalniy'
    get '/contacts' => 'static_pages#contacts'
    get '/realization' => 'static_pages#realization'
  end
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/controllers/admin/tags_controller.rb
class Admin::TagsController < Admin::ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(tag_params)
      if @tag.save
        redirect_to admin_tags_path
      else
        render :new
      end
    end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])
    if @tag.update(tag_params)
    redirect_to admin_tags_path
    else
    render 'edit'
    end
    end


  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tag
      @tag = Tag.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tag_params
      params.require(:tag).permit(:description, :keywords, :item, :title)
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/admin/tags/_form.html.erb
<%= form_for [:admin, @tag], html: { multipart: true } do |form| %>
  <% if tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_area :title, id: :tag_description %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :tag_description %>
  </div>

  <div class="field">
    <%= form.label :keywords %>
    <%= form.text_area :keywords, id: :tag_keywords %>
  </div>
  <div class="field">
  <%= form.label :Принадлежит %>
  <%= form.select :item, [['ГЛАВНАЯ'], ['LAKE VILLA'], ['РАСПОЛОЖЕНИЕ'], ['ГЕНПЛАН'], ['ДОМА'], ['ЦЕНЫ'], ['ГАЛЕРЕЯ'], ['КОНТАКТЫ']], class: 'form-control', id: 'exampleFormControlSelect1' %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/tags/edit.html.erb
<h1>Editing Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Show', admin_tags_path(tag) %> |
<%= link_to 'Back', admin_tags_path %>

app/views/admin/tags/index.html.erb
<h1>Теги</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Keywords</th>
      <th>Item</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tags.each do |tag| %>
      <tr>
        <td><%= tag.title %></td>
        <td><%= tag.description %></td>
        <td><%= tag.keywords %></td>
        <td><%= tag.item %></td>
        <td><%= link_to 'Редактировать', edit_admin_tag_path(tag), class: 'btn btn-default' %></td>
        <td><%= link_to 'Удалить', admin_tag_path(tag), class: 'btn btn-default',
        method: :delete,
        data: { confirm: 'Продолжить?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Создать теги', new_admin_tag_path, class: 'btn btn-default' %>

app/views/admin/tags/new.html.erb
<h1>New Tag</h1>

<%= render 'form', tag: @tag %>

<%= link_to 'Back', admin_tags_path %>

app/views/admin/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @tag.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @tag.description %>
</p>

<p>
  <strong>Keywords:</strong>
  <%= @tag.keywords %>
</p>

<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>