config/routes.rb
Rails.application.routes.draw do
  get '/home' => 'static_pages#home'
  get '/lakevilla' => 'static_pages#lakevilla'
  get '/location' => 'static_pages#location'
  get '/genplan' => 'static_pages#genplan'
  get '/gallery' => 'static_pages#gallery'
  get '/prices' => 'static_pages#prices'
  get '/infrastructure' => 'static_pages#infrastructure'
  get '/houses' => 'static_pages#houses'

  get '/realization' => 'static_pages#realization'
  get '/indivdesign' =>  'static_pages#indivdesign'
  get '/finishedhouse' =>  'static_pages#finishedhouse'
  get '/buildingprocess' =>  'static_pages#buildingprocess'
  get '/improvement' =>  'static_pages#improvement'
  get '/lakevilla' =>  'static_pages#lakevilla'
  get '/kivarinruchey' =>  'static_pages#kivarinruchey'
  get '/zerkalniy' =>  'static_pages#zerkalniy'
  get '/contacts' => 'static_pages#contacts'
  root 'static_pages#home'
  resources :sales do
    resources :gallerysales
    resources :relcovers
    resources :pics
  end
  resources :sheets do
    resources :smodels
  end
  resources :comments
  resources :models do
    resources :model_images
    resources :model_picture
    resources :model_galleries
  end
  namespace :admin do
    resources :model_tables
    resources :sales do
      resources :relcovers
      resources :pics
    end
    resources :tags
    resources :covers
    resources :pictures
    resources :model_pictures
    resources :models do
      resources :model_images
      resources :model_galleries
    end
    resources :sheets do
      resources :smodels
    end
    resources :galleries
    resources :tables

    resources :comments
    get '/home' => 'static_pages#home'
    get '/lakevilla' => 'static_pages#lakevilla'
    get '/location' => 'static_pages#location'
    get '/genplan' => 'static_pages#genplan'
    get '/infrastructure' => 'static_pages#infrastructure'
    get '/houses' => 'static_pages#houses'
    root 'static_pages#home'
    get '/nordplan' => 'static_pages#nordplan'
    get '/building' => 'static_pages#building'
    get '/villages' => 'static_pages#villages'
    get '/gallery' => 'static_pages#gallery'
    get '/prices' => 'static_pages#prices'
    get '/earth' => 'static_pages#earth'
    get '/projects' => 'static_pages#projects'
    get '/sale' => 'static_pages#sale'
    get '/gazobeton' =>  'static_pages#gazobeton'
    get '/karkas' =>  'static_pages#karkas'
    get '/krovlya' =>  'static_pages#krovlya'
    get '/monolit' =>  'static_pages#monolit'
    get '/systems' =>  'static_pages#systems'
    get '/fundament' =>  'static_pages#fundament'
    get '/europeanprojects' =>  'static_pages#europeanprojects'
    get '/nordplanprojects' =>  'static_pages#nordplanprojects'
    get '/indivdesign' =>  'static_pages#indivdesign'
    get '/finishrdhouse' =>  'static_pages#finishrdhouse'
    get '/buildingprocess' =>  'static_pages#buildingprocess'
    get '/improvement' =>  'static_pages#improvement'
    get '/lakevilla' =>  'static_pages#lakevilla'
    get '/kivarinruchey' =>  'static_pages#kivarinruchey'
    get '/zerkalniy' =>  'static_pages#zerkalniy'
    get '/contacts' => 'static_pages#contacts'
    get '/realization' => 'static_pages#realization'
  end
end

app/models/relcover.rb
class Relcover < ApplicationRecord
  include Paperclip::Glue
  has_attached_file :photo, styles: { big: "1200x500>", medium: "600x375>", small: "500x300>" }
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\z/

  belongs_to :sale
end

app/controllers/admin/relcovers_controller.rb
class Admin::RelcoversController < Admin::ApplicationController
  def create
    @sale = Sale.find(params[:sale_id])
    @relcover = @sale.relcovers.create(relcover_params)
  end
  def show
    @sale = Sale.find(params[:sale_id])
    @relcover = @sale.relcovers.find(params[:id])
  end
  def update
    @sale = Sale.find(params[:sale_id])
    if @sale.update(relcovers_params)
      redirect_to admin_sale_path
    else
      render 'edit'
    end
  end
  def destroy
    @sale = Sale.find(params[:sale_id])
    @relcover = @sale.relcovers.find(params[:id])
    @relcover.destroy
    redirect_to admin_sale_path(@sale)
  end
  private
    def relcover_params
      params.require(:relcover).permit(:photo)
    end
end

app/controllers/relcovers_controller.rb
class RelcoversController < ApplicationController
  def create
    @sale = Sale.find(params[:sale_id])
    @relcover = @sale.relcovers.create(relcover_params)
  end
  def show
    @sale = Sale.find(params[:sale_id])
    @relcover = @sale.relcovers.find(params[:id])
  end
  private
    def relcover_params
      params.require(:relcover).permit(:photo)
    end
end

app/helpers/relcovers_helper.rb
module RelcoversHelper
end

app/views/admin/relcovers/_form.html.erb
  <%= form_for [:admin, @relcover], html: { multipart: true } do |form| %>

  <% if relcover.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(relcover.errors.count, "error") %> prohibited this relcover from being saved:</h2>

      <ul>
      <% relcover.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %> <br>
    <%= form.text_field :title %> <br>
    <%= form.label :subtitle %>
 <br>    <%= form.text_field :subtitle %>
    <br> <%= form.label :text %>
  <br> <%= form.text_area :text %>
  <br>  <%= form.file_field :photo %>
   <br>  <%= form.label :sale_id %>
   <br>  <%= form.text_field :sale_id, id: :relcover_sale_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/relcovers/edit.html.erb
<h1>Editing Relcover</h1>

<%= render 'form', relcover: @relcover %>

<%= link_to 'Show', @relcover %> |
<%= link_to 'Back', relcovers_path %>

app/views/admin/relcovers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Relcovers</h1>

<table>
  <thead>
    <tr>
      <th>Sale</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relcovers.each do |relcover| %>
      <tr>
        <td><%= relcover.title %></td>
        <td><%= relcover.subtitle %></td>
        <td><%= relcover.text %></td>
        <td><%= relcover.sale %></td>
        <td><%= image_tag relcover.photo.url(:small) %></td>
        <td><%= link_to 'Edit', edit_admin_relcover_path(relcover) %></td>
        <td><%= link_to 'Destroy', admin_relcover_path(relcover), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Relcover', new_admin_relcover_path %>

app/views/admin/relcovers/new.html.erb
<h1>New Relcover</h1>

<%= render 'form', relcover: @relcover %>

<%= link_to 'Back', admin_relcovers_path %>

app/views/admin/relcovers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Sale:</strong>
  <%= @relcover.sale %>
</p>

<%= link_to 'Edit', edit_admin_relcover_path(@relcover) %> |
<%= link_to 'Back', admin_relcovers_path %>